[package]
name = "dustbox"
version = "0.1.0"
authors = ["Martin Lindhe"]

[lib]
path = "src/lib.rs"

[dependencies]
time = "0.1"
rand = "0.4"
tera = "0.10"
raster = "0.2"

[dev-dependencies]
bencher = "0.1"

[[bench]]
name = "cpu"
harness = false

[workspace]
members = [ "debugger" ]
