[package]
name = "dustbox"
version = "0.1.0"
authors = ["Martin Lindhe"]

[lib]
path = "src/lib.rs"

[dependencies]
time = "0.1"
rand = "0.4"
gdk = "0.7"
gdk-pixbuf = "0.3"
cairo-rs = "0.3"
raster = "0.2"
tera = "0.10"

[dev-dependencies]
bencher = "0.1"

[dependencies.gtk]
version = "0.3"
features = ["v3_10"]

[[bench]]
name = "cpu"
harness = false

[profile.release]
debug = true
