[package]
name = "dustbox_debugger"
version = "0.1.0"
authors = ["Martin Lindhe"]

[lib]
path = "src/lib.rs"

[dependencies]
cairo-rs = "0.6"
dustbox = { path = "../" }
gdk = "0.10"
gdk-pixbuf = "0.6"
#rusqlite = "0.14"

[dependencies.gtk]
version = "0.6"
features = ["v3_16"]
